languate: ruby
rvm:
  - 2.4
before_install:
- export TZ=America/Los_Angeles
install:
  - bundle install --jobs=2 --with=test
script:
  - bundle exec jekyll build --config _config.yml,_config_dev.yml
  - bundle exec jekyll serve &
  - sleep 3
  - bundle exec rake test
