languate: ruby
rvm:
  - 2.4
before_install:
- export TZ=America/Los_Angeles
install:
  - bundle install --jobs=2 --with=test
script:
  - bundle exec jekyll build
  - cd _site && bundle exec check-links
