title: Alex Mooney's Blog
description: >
  Mostly about coding, with other stuff sprinkled in
baseurl: ""
url: "https://AlexMooney.github.io"
permalink: /:categories/:year-:month-:day/:title

email: AlexMMooney@gmail.com
github_username: AlexMooney

markdown: kramdown
theme: jekyll-theme-hacker
show_downloads: false
google_analytics: 'UA-104407516-1'

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor/bundle/
