title: Alex's Blog
descrption: >
  Stuff about coding and pen and paper RPGs
baseurl: ""
url: "https://AlexMooney.github.io"
permalink: /:categories/:title/

email: AlexMMooney@gmail.com
github_username: AlexMooney

markdown: kramdown
theme: jekyll-theme-hacker
show_downloads: false
google_analytics: 'UA-104407516-1'

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor/bundle/
